spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 251084
    url: jdbc:postgresql://localhost:5432/social
    platform: postgres
    initialization-mode: never
    continue-on-error: true
    schema: classpath:/sql/user-schema.sql, classpath:/sql/posts-schema.sql
    data: classpath:/sql/user-data.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: info
    org.springframework.web: info
  pattern:
    console: "%d %-5level %logger : %msg%n"